# Generated by Django 6.0.6 on 2026-06-11 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('cutoff_time', models.TimeField()),
                ('delivery_start_time', models.TimeField()),
                ('delivery_end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['delivery_start_time'],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_slot_name_per_restaurant')],
            },
        ),
    ]
