# Generated by Django 6.0.6 on 2026-06-11 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_locations', '0001_initial'),
        ('menus', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('slots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CHECKED_OUT', 'Checked Out'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery_locations.deliverylocation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slots.deliveryslot')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.menuitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['customer', 'status'], name='cart_cart_custome_17ff89_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['restaurant'], name='cart_cart_restaur_f211c3_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['delivery_date'], name='cart_cart_deliver_ad884b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('customer',), name='one_active_cart_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'menu_item'), name='unique_menu_item_per_cart'),
        ),
    ]
