# Generated by Django 6.0.6 on 2026-06-19 17:20

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email_auth'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.EmailUserManager()),
            ],
        ),
    ]
