# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverylocation",
            name="image",
            field=models.ImageField(blank=True, upload_to="delivery-locations/"),
        ),
    ]
